### ISSUE TITLE
float32 parsed as float16

### ISSUE THREAD

**Issue by chaosink** [cheind/py-minexr#3]
Test file: [test.zip](https://github.com/cheind/py-minexr/files/7348624/test.zip)

**Comment by chaosink** [comment]
Just notice "no pixel data compression".
Close for the moment.

**Comment by cheind** [comment]
What's happening? :)

**Comment by cheind** [comment]
I'm quite unhappy with zip files being uploaded to github. would you mind explaining what it contains?
